[WNC-32] add message when staff add amount for account
21CLC01-WNC-Banking/WNC-Banking-BE pull request #29
Opened 2024-12-27 16:04 UTC by Tricker14

2024-12-27 17:51 UTC, VuKhoa23 requested changes

2024-12-27 17:51 UTC, VuKhoa23 commented on internal/service/implement/staff_service.go
> -		Description:         "staff add amount to account",
Dùng cái message này nè. Cái message ở trên ko có ý nghĩa

2024-12-27 17:52 UTC, VuKhoa23 requested changes

2024-12-27 17:52 UTC, VuKhoa23 commented on internal/domain/model/staff.go
> +	Message       string `json:"message"`
Description chứ ko phải message

2024-12-28 01:10 UTC, Tricker14 commented on internal/service/implement/staff_service.go
> -		Description:         "staff add amount to account",
changed message

2024-12-28 01:10 UTC, Tricker14 commented on internal/domain/model/staff.go
> +	Message       string `json:"message"`
changed from description

2024-12-28 01:26 UTC, VuKhoa23 approved these changes
Lgtm

2024-12-28 01:34 UTC, merged